plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_87"))
    implementation(project(":layer_1:module_1_82"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_124"))
    implementation(project(":layer_1:module_1_148"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_97"))
    implementation(project(":layer_1:module_1_125"))
    implementation(project(":layer_1:module_1_93"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_94"))
    implementation(project(":layer_1:module_1_127"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_135"))
    implementation(project(":layer_1:module_1_147"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_150"))
    implementation(project(":layer_1:module_1_118"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_114"))
    implementation(project(":layer_1:module_1_99"))
    implementation(project(":layer_1:module_1_104"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_157"))
    implementation(project(":layer_1:module_1_91"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_128"))
}