plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_106"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_152"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_93"))
    implementation(project(":layer_1:module_1_141"))
    implementation(project(":layer_1:module_1_114"))
    implementation(project(":layer_1:module_1_85"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_113"))
    implementation(project(":layer_1:module_1_90"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_83"))
    implementation(project(":layer_1:module_1_97"))
    implementation(project(":layer_1:module_1_103"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_115"))
    implementation(project(":layer_1:module_1_101"))
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_108"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_151"))
    implementation(project(":layer_1:module_1_104"))
    implementation(project(":layer_1:module_1_119"))
}