plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_20"))
}