plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_124"))
    implementation(project(":layer_1:module_1_145"))
    implementation(project(":layer_1:module_1_152"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_156"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_117"))
    implementation(project(":layer_1:module_1_125"))
    implementation(project(":layer_1:module_1_86"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_99"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_87"))
    implementation(project(":layer_1:module_1_146"))
    implementation(project(":layer_1:module_1_151"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_160"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_122"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_149"))
    implementation(project(":layer_1:module_1_91"))
    implementation(project(":layer_1:module_1_90"))
    implementation(project(":layer_1:module_1_114"))
}