plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_92"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_157"))
    implementation(project(":layer_1:module_1_149"))
    implementation(project(":layer_1:module_1_144"))
    implementation(project(":layer_1:module_1_133"))
    implementation(project(":layer_1:module_1_82"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_146"))
    implementation(project(":layer_1:module_1_100"))
    implementation(project(":layer_1:module_1_156"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_107"))
    implementation(project(":layer_1:module_1_86"))
    implementation(project(":layer_1:module_1_104"))
    implementation(project(":layer_1:module_1_101"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_105"))
    implementation(project(":layer_1:module_1_103"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_99"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_94"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_122"))
}