plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_91"))
    implementation(project(":layer_1:module_1_97"))
    implementation(project(":layer_1:module_1_134"))
    implementation(project(":layer_1:module_1_117"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_85"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_157"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_143"))
    implementation(project(":layer_1:module_1_105"))
    implementation(project(":layer_1:module_1_155"))
    implementation(project(":layer_1:module_1_149"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_107"))
    implementation(project(":layer_1:module_1_160"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_83"))
    implementation(project(":layer_1:module_1_106"))
    implementation(project(":layer_1:module_1_148"))
    implementation(project(":layer_1:module_1_140"))
    implementation(project(":layer_1:module_1_151"))
    implementation(project(":layer_1:module_1_110"))
}