plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_198"))
    implementation(project(":layer_2:module_2_229"))
    implementation(project(":layer_2:module_2_169"))
    implementation(project(":layer_2:module_2_215"))
    implementation(project(":layer_2:module_2_175"))
    implementation(project(":layer_2:module_2_203"))
    implementation(project(":layer_2:module_2_228"))
    implementation(project(":layer_2:module_2_182"))
    implementation(project(":layer_2:module_2_235"))
    implementation(project(":layer_2:module_2_238"))
    implementation(project(":layer_2:module_2_237"))
    implementation(project(":layer_2:module_2_168"))
    implementation(project(":layer_2:module_2_170"))
    implementation(project(":layer_2:module_2_179"))
    implementation(project(":layer_2:module_2_222"))
    implementation(project(":layer_2:module_2_166"))
    implementation(project(":layer_2:module_2_192"))
    implementation(project(":layer_2:module_2_177"))
    implementation(project(":layer_2:module_2_173"))
    implementation(project(":layer_2:module_2_223"))
    implementation(project(":layer_2:module_2_193"))
    implementation(project(":layer_2:module_2_207"))
    implementation(project(":layer_2:module_2_202"))
    implementation(project(":layer_2:module_2_174"))
    implementation(project(":layer_2:module_2_172"))
    implementation(project(":layer_2:module_2_200"))
    implementation(project(":layer_2:module_2_197"))
    implementation(project(":layer_2:module_2_161"))
    implementation(project(":layer_2:module_2_165"))
}