plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_42"))
}