plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_163"))
    implementation(project(":layer_2:module_2_174"))
    implementation(project(":layer_2:module_2_199"))
    implementation(project(":layer_2:module_2_184"))
    implementation(project(":layer_2:module_2_175"))
    implementation(project(":layer_2:module_2_166"))
    implementation(project(":layer_2:module_2_176"))
    implementation(project(":layer_2:module_2_195"))
    implementation(project(":layer_2:module_2_230"))
    implementation(project(":layer_2:module_2_227"))
    implementation(project(":layer_2:module_2_201"))
    implementation(project(":layer_2:module_2_162"))
    implementation(project(":layer_2:module_2_185"))
    implementation(project(":layer_2:module_2_173"))
    implementation(project(":layer_2:module_2_168"))
    implementation(project(":layer_2:module_2_232"))
    implementation(project(":layer_2:module_2_189"))
    implementation(project(":layer_2:module_2_205"))
    implementation(project(":layer_2:module_2_186"))
    implementation(project(":layer_2:module_2_180"))
    implementation(project(":layer_2:module_2_225"))
    implementation(project(":layer_2:module_2_218"))
    implementation(project(":layer_2:module_2_203"))
    implementation(project(":layer_2:module_2_202"))
    implementation(project(":layer_2:module_2_221"))
    implementation(project(":layer_2:module_2_164"))
    implementation(project(":layer_2:module_2_236"))
    implementation(project(":layer_2:module_2_177"))
}