plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_3:module_3_299"))
    implementation(project(":layer_3:module_3_297"))
    implementation(project(":layer_3:module_3_314"))
    implementation(project(":layer_3:module_3_310"))
    implementation(project(":layer_3:module_3_252"))
    implementation(project(":layer_3:module_3_320"))
    implementation(project(":layer_3:module_3_316"))
    implementation(project(":layer_3:module_3_318"))
    implementation(project(":layer_3:module_3_275"))
    implementation(project(":layer_3:module_3_261"))
    implementation(project(":layer_3:module_3_285"))
    implementation(project(":layer_3:module_3_279"))
    implementation(project(":layer_3:module_3_256"))
    implementation(project(":layer_3:module_3_307"))
    implementation(project(":layer_3:module_3_302"))
    implementation(project(":layer_3:module_3_243"))
    implementation(project(":layer_3:module_3_298"))
    implementation(project(":layer_3:module_3_258"))
    implementation(project(":layer_3:module_3_294"))
    implementation(project(":layer_3:module_3_254"))
    implementation(project(":layer_3:module_3_278"))
    implementation(project(":layer_3:module_3_251"))
    implementation(project(":layer_3:module_3_255"))
    implementation(project(":layer_3:module_3_282"))
    implementation(project(":layer_3:module_3_244"))
    implementation(project(":layer_3:module_3_270"))
    implementation(project(":layer_3:module_3_259"))
    implementation(project(":layer_3:module_3_287"))
}