plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_149"))
    implementation(project(":layer_1:module_1_160"))
    implementation(project(":layer_1:module_1_105"))
    implementation(project(":layer_1:module_1_103"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_83"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_87"))
    implementation(project(":layer_1:module_1_159"))
    implementation(project(":layer_1:module_1_151"))
    implementation(project(":layer_1:module_1_139"))
    implementation(project(":layer_1:module_1_88"))
    implementation(project(":layer_1:module_1_107"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_147"))
    implementation(project(":layer_1:module_1_146"))
    implementation(project(":layer_1:module_1_115"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_82"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_145"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_144"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_118"))
    implementation(project(":layer_1:module_1_92"))
}