plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_238"))
    implementation(project(":layer_2:module_2_172"))
    implementation(project(":layer_2:module_2_217"))
    implementation(project(":layer_2:module_2_174"))
    implementation(project(":layer_2:module_2_223"))
    implementation(project(":layer_2:module_2_192"))
    implementation(project(":layer_2:module_2_216"))
    implementation(project(":layer_2:module_2_170"))
    implementation(project(":layer_2:module_2_164"))
    implementation(project(":layer_2:module_2_232"))
    implementation(project(":layer_2:module_2_225"))
    implementation(project(":layer_2:module_2_185"))
    implementation(project(":layer_2:module_2_202"))
    implementation(project(":layer_2:module_2_228"))
    implementation(project(":layer_2:module_2_231"))
    implementation(project(":layer_2:module_2_211"))
    implementation(project(":layer_2:module_2_199"))
    implementation(project(":layer_2:module_2_178"))
    implementation(project(":layer_2:module_2_201"))
    implementation(project(":layer_2:module_2_163"))
    implementation(project(":layer_2:module_2_212"))
    implementation(project(":layer_2:module_2_207"))
    implementation(project(":layer_2:module_2_234"))
    implementation(project(":layer_2:module_2_167"))
    implementation(project(":layer_2:module_2_229"))
    implementation(project(":layer_2:module_2_226"))
    implementation(project(":layer_2:module_2_186"))
    implementation(project(":layer_2:module_2_168"))
}