plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_31"))
}