plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_210"))
    implementation(project(":layer_2:module_2_240"))
    implementation(project(":layer_2:module_2_178"))
    implementation(project(":layer_2:module_2_203"))
    implementation(project(":layer_2:module_2_234"))
    implementation(project(":layer_2:module_2_236"))
    implementation(project(":layer_2:module_2_166"))
    implementation(project(":layer_2:module_2_233"))
    implementation(project(":layer_2:module_2_177"))
    implementation(project(":layer_2:module_2_216"))
    implementation(project(":layer_2:module_2_182"))
    implementation(project(":layer_2:module_2_237"))
    implementation(project(":layer_2:module_2_169"))
    implementation(project(":layer_2:module_2_172"))
    implementation(project(":layer_2:module_2_213"))
    implementation(project(":layer_2:module_2_206"))
    implementation(project(":layer_2:module_2_208"))
    implementation(project(":layer_2:module_2_217"))
    implementation(project(":layer_2:module_2_191"))
    implementation(project(":layer_2:module_2_232"))
    implementation(project(":layer_2:module_2_220"))
    implementation(project(":layer_2:module_2_205"))
    implementation(project(":layer_2:module_2_207"))
    implementation(project(":layer_2:module_2_190"))
    implementation(project(":layer_2:module_2_222"))
    implementation(project(":layer_2:module_2_202"))
    implementation(project(":layer_2:module_2_221"))
    implementation(project(":layer_2:module_2_163"))
    implementation(project(":layer_2:module_2_224"))
    implementation(project(":layer_2:module_2_185"))
    implementation(project(":layer_2:module_2_180"))
    implementation(project(":layer_2:module_2_179"))
}