plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_3:module_3_315"))
    implementation(project(":layer_3:module_3_303"))
    implementation(project(":layer_3:module_3_247"))
    implementation(project(":layer_3:module_3_268"))
    implementation(project(":layer_3:module_3_296"))
    implementation(project(":layer_3:module_3_258"))
    implementation(project(":layer_3:module_3_273"))
    implementation(project(":layer_3:module_3_317"))
    implementation(project(":layer_3:module_3_272"))
    implementation(project(":layer_3:module_3_294"))
    implementation(project(":layer_3:module_3_249"))
    implementation(project(":layer_3:module_3_316"))
    implementation(project(":layer_3:module_3_254"))
    implementation(project(":layer_3:module_3_275"))
    implementation(project(":layer_3:module_3_298"))
    implementation(project(":layer_3:module_3_269"))
    implementation(project(":layer_3:module_3_306"))
    implementation(project(":layer_3:module_3_278"))
    implementation(project(":layer_3:module_3_255"))
    implementation(project(":layer_3:module_3_295"))
    implementation(project(":layer_3:module_3_308"))
    implementation(project(":layer_3:module_3_263"))
    implementation(project(":layer_3:module_3_310"))
    implementation(project(":layer_3:module_3_284"))
}