plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_3:module_3_295"))
    implementation(project(":layer_3:module_3_319"))
    implementation(project(":layer_3:module_3_263"))
    implementation(project(":layer_3:module_3_267"))
    implementation(project(":layer_3:module_3_260"))
    implementation(project(":layer_3:module_3_243"))
    implementation(project(":layer_3:module_3_298"))
    implementation(project(":layer_3:module_3_299"))
    implementation(project(":layer_3:module_3_256"))
    implementation(project(":layer_3:module_3_275"))
    implementation(project(":layer_3:module_3_253"))
    implementation(project(":layer_3:module_3_265"))
    implementation(project(":layer_3:module_3_316"))
    implementation(project(":layer_3:module_3_278"))
    implementation(project(":layer_3:module_3_312"))
    implementation(project(":layer_3:module_3_280"))
    implementation(project(":layer_3:module_3_273"))
    implementation(project(":layer_3:module_3_286"))
    implementation(project(":layer_3:module_3_248"))
    implementation(project(":layer_3:module_3_241"))
    implementation(project(":layer_3:module_3_313"))
    implementation(project(":layer_3:module_3_259"))
    implementation(project(":layer_3:module_3_303"))
    implementation(project(":layer_3:module_3_318"))
    implementation(project(":layer_3:module_3_293"))
    implementation(project(":layer_3:module_3_304"))
    implementation(project(":layer_3:module_3_285"))
    implementation(project(":layer_3:module_3_289"))
}