plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_209"))
    implementation(project(":layer_2:module_2_182"))
    implementation(project(":layer_2:module_2_188"))
    implementation(project(":layer_2:module_2_235"))
    implementation(project(":layer_2:module_2_189"))
    implementation(project(":layer_2:module_2_210"))
    implementation(project(":layer_2:module_2_219"))
    implementation(project(":layer_2:module_2_192"))
    implementation(project(":layer_2:module_2_232"))
    implementation(project(":layer_2:module_2_208"))
    implementation(project(":layer_2:module_2_236"))
    implementation(project(":layer_2:module_2_205"))
    implementation(project(":layer_2:module_2_180"))
    implementation(project(":layer_2:module_2_200"))
    implementation(project(":layer_2:module_2_222"))
    implementation(project(":layer_2:module_2_220"))
    implementation(project(":layer_2:module_2_184"))
    implementation(project(":layer_2:module_2_207"))
    implementation(project(":layer_2:module_2_225"))
    implementation(project(":layer_2:module_2_166"))
    implementation(project(":layer_2:module_2_196"))
    implementation(project(":layer_2:module_2_183"))
    implementation(project(":layer_2:module_2_216"))
    implementation(project(":layer_2:module_2_178"))
    implementation(project(":layer_2:module_2_187"))
    implementation(project(":layer_2:module_2_226"))
    implementation(project(":layer_2:module_2_197"))
    implementation(project(":layer_2:module_2_167"))
    implementation(project(":layer_2:module_2_234"))
    implementation(project(":layer_2:module_2_230"))
    implementation(project(":layer_2:module_2_211"))
    implementation(project(":layer_2:module_2_175"))
}