plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_22"))
}