plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_31"))
}