plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_229"))
    implementation(project(":layer_2:module_2_194"))
    implementation(project(":layer_2:module_2_223"))
    implementation(project(":layer_2:module_2_190"))
    implementation(project(":layer_2:module_2_182"))
    implementation(project(":layer_2:module_2_236"))
    implementation(project(":layer_2:module_2_211"))
    implementation(project(":layer_2:module_2_216"))
    implementation(project(":layer_2:module_2_212"))
    implementation(project(":layer_2:module_2_233"))
    implementation(project(":layer_2:module_2_210"))
    implementation(project(":layer_2:module_2_214"))
    implementation(project(":layer_2:module_2_164"))
    implementation(project(":layer_2:module_2_170"))
    implementation(project(":layer_2:module_2_169"))
    implementation(project(":layer_2:module_2_213"))
    implementation(project(":layer_2:module_2_224"))
    implementation(project(":layer_2:module_2_201"))
    implementation(project(":layer_2:module_2_175"))
    implementation(project(":layer_2:module_2_215"))
    implementation(project(":layer_2:module_2_166"))
    implementation(project(":layer_2:module_2_218"))
    implementation(project(":layer_2:module_2_174"))
    implementation(project(":layer_2:module_2_238"))
    implementation(project(":layer_2:module_2_227"))
    implementation(project(":layer_2:module_2_225"))
    implementation(project(":layer_2:module_2_222"))
    implementation(project(":layer_2:module_2_220"))
    implementation(project(":layer_2:module_2_203"))
    implementation(project(":layer_2:module_2_168"))
    implementation(project(":layer_2:module_2_226"))
    implementation(project(":layer_2:module_2_185"))
}