plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_40"))
}