plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_93"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_114"))
    implementation(project(":layer_1:module_1_100"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_155"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_127"))
    implementation(project(":layer_1:module_1_103"))
    implementation(project(":layer_1:module_1_147"))
    implementation(project(":layer_1:module_1_105"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_157"))
    implementation(project(":layer_1:module_1_87"))
    implementation(project(":layer_1:module_1_97"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_82"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_154"))
    implementation(project(":layer_1:module_1_144"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_125"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_85"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_134"))
}