plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_104"))
    implementation(project(":layer_1:module_1_117"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_106"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_139"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_122"))
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_157"))
    implementation(project(":layer_1:module_1_88"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_85"))
    implementation(project(":layer_1:module_1_93"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_135"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_87"))
    implementation(project(":layer_1:module_1_129"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_134"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_160"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_137"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_113"))
    implementation(project(":layer_1:module_1_111"))
}