plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_99"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_148"))
    implementation(project(":layer_1:module_1_155"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_103"))
    implementation(project(":layer_1:module_1_92"))
    implementation(project(":layer_1:module_1_82"))
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_143"))
    implementation(project(":layer_1:module_1_117"))
    implementation(project(":layer_1:module_1_88"))
    implementation(project(":layer_1:module_1_101"))
    implementation(project(":layer_1:module_1_105"))
    implementation(project(":layer_1:module_1_135"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_147"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_152"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_121"))
}