plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_2:module_2_208"))
    implementation(project(":layer_2:module_2_220"))
    implementation(project(":layer_2:module_2_190"))
    implementation(project(":layer_2:module_2_178"))
    implementation(project(":layer_2:module_2_229"))
    implementation(project(":layer_2:module_2_162"))
    implementation(project(":layer_2:module_2_182"))
    implementation(project(":layer_2:module_2_179"))
    implementation(project(":layer_2:module_2_206"))
    implementation(project(":layer_2:module_2_189"))
    implementation(project(":layer_2:module_2_195"))
    implementation(project(":layer_2:module_2_232"))
    implementation(project(":layer_2:module_2_218"))
    implementation(project(":layer_2:module_2_193"))
    implementation(project(":layer_2:module_2_238"))
    implementation(project(":layer_2:module_2_171"))
    implementation(project(":layer_2:module_2_228"))
    implementation(project(":layer_2:module_2_191"))
    implementation(project(":layer_2:module_2_222"))
    implementation(project(":layer_2:module_2_172"))
    implementation(project(":layer_2:module_2_213"))
    implementation(project(":layer_2:module_2_201"))
    implementation(project(":layer_2:module_2_174"))
    implementation(project(":layer_2:module_2_199"))
    implementation(project(":layer_2:module_2_227"))
    implementation(project(":layer_2:module_2_200"))
    implementation(project(":layer_2:module_2_188"))
    implementation(project(":layer_2:module_2_240"))
    implementation(project(":layer_2:module_2_167"))
}