plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_153"))
    implementation(project(":layer_1:module_1_159"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_141"))
    implementation(project(":layer_1:module_1_86"))
    implementation(project(":layer_1:module_1_92"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_147"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_85"))
    implementation(project(":layer_1:module_1_107"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_117"))
    implementation(project(":layer_1:module_1_137"))
    implementation(project(":layer_1:module_1_87"))
    implementation(project(":layer_1:module_1_113"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_129"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_100"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_156"))
    implementation(project(":layer_1:module_1_106"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_94"))
}