plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_72"))
}