plugins {
    id("awesome.kotlin.plugin")
}

dependencies {
    implementation(project(":layer_3:module_3_315"))
    implementation(project(":layer_3:module_3_254"))
    implementation(project(":layer_3:module_3_265"))
    implementation(project(":layer_3:module_3_281"))
    implementation(project(":layer_3:module_3_259"))
    implementation(project(":layer_3:module_3_244"))
    implementation(project(":layer_3:module_3_242"))
    implementation(project(":layer_3:module_3_311"))
    implementation(project(":layer_3:module_3_248"))
    implementation(project(":layer_3:module_3_320"))
    implementation(project(":layer_3:module_3_269"))
    implementation(project(":layer_3:module_3_258"))
    implementation(project(":layer_3:module_3_287"))
    implementation(project(":layer_3:module_3_286"))
    implementation(project(":layer_3:module_3_273"))
    implementation(project(":layer_3:module_3_284"))
    implementation(project(":layer_3:module_3_271"))
    implementation(project(":layer_3:module_3_299"))
    implementation(project(":layer_3:module_3_316"))
    implementation(project(":layer_3:module_3_293"))
    implementation(project(":layer_3:module_3_285"))
    implementation(project(":layer_3:module_3_290"))
    implementation(project(":layer_3:module_3_308"))
    implementation(project(":layer_3:module_3_305"))
    implementation(project(":layer_3:module_3_278"))
    implementation(project(":layer_3:module_3_264"))
    implementation(project(":layer_3:module_3_280"))
    implementation(project(":layer_3:module_3_272"))
    implementation(project(":layer_3:module_3_291"))
    implementation(project(":layer_3:module_3_307"))
    implementation(project(":layer_3:module_3_295"))
}